# Define the base linux distribution.
FROM ubuntu/apache2:latest

# Define the maintainer of the project.
LABEL maintainer="calegariluisfernando@gmail.com"

# Set default work directory.
# WORKDIR /var/www/html

# Set the default port.
EXPOSE 80 443

# Boot script.
# ENTRYPOINT ["/entrypoint.sh"]