version: '3.9'

services:
  frontend:
    image: ${REPOSITORY_URL}/${REPOSITORY_ID}/rifei-frontend:latest
    container_name: rifei-frontend
    hostname: rifei-frontend
    ports:
      - "80:80"
      - "443:443"
      
volumes:
  database-data: